services:
  mysql:
    image: mariadb:10.5.8
    container_name: dirt_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: dirt_backend
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      PORT: 3001
      APP_PASSCODE: ${APP_PASSCODE}
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: dirt_frontend
    restart: unless-stopped
    ports:
      - "7001:80"
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: dirt_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "7002:80"
    depends_on:
      - mysql

